// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/search/search.proto

/*
Package search is a generated protocol buffer package.

It is generated from these files:
	pb/search/search.proto

It has these top-level messages:
	NearbyRequest
	SearchResult
*/
package search

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NearbyRequest struct {
	Lat     float32 `protobuf:"fixed32,1,opt,name=lat" json:"lat,omitempty"`
	Lon     float32 `protobuf:"fixed32,2,opt,name=lon" json:"lon,omitempty"`
	InDate  string  `protobuf:"bytes,3,opt,name=inDate" json:"inDate,omitempty"`
	OutDate string  `protobuf:"bytes,4,opt,name=outDate" json:"outDate,omitempty"`
}

func (m *NearbyRequest) Reset()                    { *m = NearbyRequest{} }
func (m *NearbyRequest) String() string            { return proto.CompactTextString(m) }
func (*NearbyRequest) ProtoMessage()               {}
func (*NearbyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NearbyRequest) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *NearbyRequest) GetLon() float32 {
	if m != nil {
		return m.Lon
	}
	return 0
}

func (m *NearbyRequest) GetInDate() string {
	if m != nil {
		return m.InDate
	}
	return ""
}

func (m *NearbyRequest) GetOutDate() string {
	if m != nil {
		return m.OutDate
	}
	return ""
}

type SearchResult struct {
	HotelIds []string `protobuf:"bytes,1,rep,name=hotelIds" json:"hotelIds,omitempty"`
}

func (m *SearchResult) Reset()                    { *m = SearchResult{} }
func (m *SearchResult) String() string            { return proto.CompactTextString(m) }
func (*SearchResult) ProtoMessage()               {}
func (*SearchResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SearchResult) GetHotelIds() []string {
	if m != nil {
		return m.HotelIds
	}
	return nil
}

func init() {
	proto.RegisterType((*NearbyRequest)(nil), "search.NearbyRequest")
	proto.RegisterType((*SearchResult)(nil), "search.SearchResult")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Search service

type SearchClient interface {
	Nearby(ctx context.Context, in *NearbyRequest, opts ...grpc.CallOption) (*SearchResult, error)
}

type searchClient struct {
	cc *grpc.ClientConn
}

func NewSearchClient(cc *grpc.ClientConn) SearchClient {
	return &searchClient{cc}
}

func (c *searchClient) Nearby(ctx context.Context, in *NearbyRequest, opts ...grpc.CallOption) (*SearchResult, error) {
	out := new(SearchResult)
	err := grpc.Invoke(ctx, "/search.Search/Nearby", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Search service

type SearchServer interface {
	Nearby(context.Context, *NearbyRequest) (*SearchResult, error)
}

func RegisterSearchServer(s *grpc.Server, srv SearchServer) {
	s.RegisterService(&_Search_serviceDesc, srv)
}

func _Search_Nearby_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NearbyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServer).Nearby(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search.Search/Nearby",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServer).Nearby(ctx, req.(*NearbyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Search_serviceDesc = grpc.ServiceDesc{
	ServiceName: "search.Search",
	HandlerType: (*SearchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Nearby",
			Handler:    _Search_Nearby_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/search/search.proto",
}

func init() { proto.RegisterFile("pb/search/search.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x48, 0xd2, 0x2f,
	0x4e, 0x4d, 0x2c, 0x4a, 0xce, 0x80, 0x52, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x6c, 0x10,
	0x9e, 0x52, 0x2a, 0x17, 0xaf, 0x5f, 0x6a, 0x62, 0x51, 0x52, 0x65, 0x50, 0x6a, 0x61, 0x69, 0x6a,
	0x71, 0x89, 0x90, 0x00, 0x17, 0x73, 0x4e, 0x62, 0x89, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x53, 0x10,
	0x88, 0x09, 0x16, 0xc9, 0xcf, 0x93, 0x60, 0x82, 0x8a, 0xe4, 0xe7, 0x09, 0x89, 0x71, 0xb1, 0x65,
	0xe6, 0xb9, 0x24, 0x96, 0xa4, 0x4a, 0x30, 0x2b, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x79, 0x42, 0x12,
	0x5c, 0xec, 0xf9, 0xa5, 0x25, 0x60, 0x09, 0x16, 0xb0, 0x04, 0x8c, 0xab, 0xa4, 0xc5, 0xc5, 0x13,
	0x0c, 0xb6, 0x30, 0x28, 0xb5, 0xb8, 0x34, 0xa7, 0x44, 0x48, 0x8a, 0x8b, 0x23, 0x23, 0xbf, 0x24,
	0x35, 0xc7, 0x33, 0xa5, 0x58, 0x82, 0x51, 0x81, 0x59, 0x83, 0x33, 0x08, 0xce, 0x37, 0xb2, 0xe7,
	0x62, 0x83, 0xa8, 0x15, 0x32, 0xe5, 0x62, 0x83, 0x38, 0x4e, 0x48, 0x54, 0x0f, 0xea, 0x7a, 0x14,
	0xc7, 0x4a, 0x89, 0xc0, 0x84, 0x91, 0x0d, 0x4f, 0x62, 0x03, 0x7b, 0xd1, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0xac, 0x9e, 0x96, 0x82, 0xfc, 0x00, 0x00, 0x00,
}
