// Code generated by protoc-gen-go.
// source: proto/rate/rate.proto
// DO NOT EDIT!

/*
Package rate is a generated protocol buffer package.

It is generated from these files:
	proto/rate/rate.proto

It has these top-level messages:
	RateRequest
	RateReply
	RatePlan
	RoomType
*/
package rate

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type RateRequest struct {
	HotelIds []int32 `protobuf:"varint,1,rep,name=hotelIds" json:"hotelIds,omitempty"`
	InDate   string  `protobuf:"bytes,2,opt,name=inDate" json:"inDate,omitempty"`
	OutDate  string  `protobuf:"bytes,3,opt,name=outDate" json:"outDate,omitempty"`
}

func (m *RateRequest) Reset()                    { *m = RateRequest{} }
func (m *RateRequest) String() string            { return proto.CompactTextString(m) }
func (*RateRequest) ProtoMessage()               {}
func (*RateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type RateReply struct {
	RatePlans []*RatePlan `protobuf:"bytes,1,rep,name=ratePlans" json:"ratePlans,omitempty"`
}

func (m *RateReply) Reset()                    { *m = RateReply{} }
func (m *RateReply) String() string            { return proto.CompactTextString(m) }
func (*RateReply) ProtoMessage()               {}
func (*RateReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RateReply) GetRatePlans() []*RatePlan {
	if m != nil {
		return m.RatePlans
	}
	return nil
}

type RatePlan struct {
	HotelId  int32     `protobuf:"varint,1,opt,name=hotelId" json:"hotelId,omitempty"`
	Code     string    `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	InDate   string    `protobuf:"bytes,3,opt,name=inDate" json:"inDate,omitempty"`
	OutDate  string    `protobuf:"bytes,4,opt,name=outDate" json:"outDate,omitempty"`
	RoomType *RoomType `protobuf:"bytes,5,opt,name=roomType" json:"roomType,omitempty"`
}

func (m *RatePlan) Reset()                    { *m = RatePlan{} }
func (m *RatePlan) String() string            { return proto.CompactTextString(m) }
func (*RatePlan) ProtoMessage()               {}
func (*RatePlan) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RatePlan) GetRoomType() *RoomType {
	if m != nil {
		return m.RoomType
	}
	return nil
}

type RoomType struct {
	BookableRate       float64 `protobuf:"fixed64,1,opt,name=bookableRate" json:"bookableRate,omitempty"`
	TotalRate          float64 `protobuf:"fixed64,2,opt,name=totalRate" json:"totalRate,omitempty"`
	TotalRateInclusive float64 `protobuf:"fixed64,3,opt,name=TotalRateInclusive" json:"TotalRateInclusive,omitempty"`
	Code               string  `protobuf:"bytes,4,opt,name=code" json:"code,omitempty"`
	Currency           string  `protobuf:"bytes,5,opt,name=currency" json:"currency,omitempty"`
	RoomDescription    string  `protobuf:"bytes,6,opt,name=roomDescription" json:"roomDescription,omitempty"`
}

func (m *RoomType) Reset()                    { *m = RoomType{} }
func (m *RoomType) String() string            { return proto.CompactTextString(m) }
func (*RoomType) ProtoMessage()               {}
func (*RoomType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*RateRequest)(nil), "rate.RateRequest")
	proto.RegisterType((*RateReply)(nil), "rate.RateReply")
	proto.RegisterType((*RatePlan)(nil), "rate.RatePlan")
	proto.RegisterType((*RoomType)(nil), "rate.RoomType")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for Rate service

type RateClient interface {
	// GetRates returns rate codes for hotels for a given date range
	GetRates(ctx context.Context, in *RateRequest, opts ...grpc.CallOption) (*RateReply, error)
}

type rateClient struct {
	cc *grpc.ClientConn
}

func NewRateClient(cc *grpc.ClientConn) RateClient {
	return &rateClient{cc}
}

func (c *rateClient) GetRates(ctx context.Context, in *RateRequest, opts ...grpc.CallOption) (*RateReply, error) {
	out := new(RateReply)
	err := grpc.Invoke(ctx, "/rate.Rate/GetRates", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Rate service

type RateServer interface {
	// GetRates returns rate codes for hotels for a given date range
	GetRates(context.Context, *RateRequest) (*RateReply, error)
}

func RegisterRateServer(s *grpc.Server, srv RateServer) {
	s.RegisterService(&_Rate_serviceDesc, srv)
}

func _Rate_GetRates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(RateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(RateServer).GetRates(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _Rate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rate.Rate",
	HandlerType: (*RateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRates",
			Handler:    _Rate_GetRates_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x5c, 0x91, 0xc1, 0x4e, 0x83, 0x40,
	0x10, 0x86, 0xb3, 0x42, 0x11, 0xa6, 0x4d, 0xb1, 0x13, 0x8d, 0xa4, 0x27, 0xe4, 0xd4, 0x13, 0x26,
	0x35, 0xf1, 0xec, 0xa1, 0x89, 0xe9, 0xcd, 0x90, 0xbe, 0x00, 0xd0, 0x4d, 0x24, 0xae, 0x0c, 0x2e,
	0x8b, 0x09, 0x6f, 0xe0, 0x63, 0xbb, 0xbb, 0x80, 0x98, 0x5e, 0x60, 0xe6, 0x67, 0xf2, 0x7f, 0x3f,
	0x33, 0x70, 0xd7, 0x48, 0x52, 0xf4, 0x28, 0x73, 0xc5, 0xed, 0x23, 0xb5, 0x3d, 0xba, 0xa6, 0x4e,
	0x5e, 0x60, 0x99, 0xe9, 0x77, 0xc6, 0xbf, 0x3a, 0xde, 0x2a, 0xbc, 0x01, 0xff, 0x9d, 0x14, 0x17,
	0xc7, 0x73, 0x1b, 0xb1, 0xd8, 0xd9, 0x2d, 0x70, 0x0d, 0x5e, 0x55, 0x1f, 0xf4, 0x48, 0x74, 0x15,
	0xb3, 0x5d, 0x80, 0x21, 0x5c, 0x53, 0xa7, 0xac, 0xe0, 0x18, 0x21, 0x49, 0x21, 0x18, 0x1c, 0x1a,
	0xd1, 0xe3, 0x03, 0x04, 0xc6, 0xf6, 0x4d, 0xe4, 0xf5, 0x60, 0xb0, 0xdc, 0xaf, 0x53, 0x0b, 0xcd,
	0x46, 0x39, 0x11, 0xe0, 0x4f, 0xb5, 0x31, 0x1b, 0x71, 0x7a, 0x98, 0x69, 0xda, 0x0a, 0xdc, 0x92,
	0xce, 0x13, 0x6b, 0x66, 0x3b, 0x97, 0x6c, 0xd7, 0x0a, 0x31, 0xf8, 0x92, 0xe8, 0xf3, 0xd4, 0x37,
	0x3c, 0x5a, 0x68, 0x65, 0xa6, 0x8d, 0x6a, 0xf2, 0xc3, 0x34, 0x6e, 0x6c, 0xf0, 0x16, 0x56, 0x05,
	0xd1, 0x47, 0x5e, 0x08, 0x6e, 0x22, 0x58, 0x26, 0xc3, 0x0d, 0x04, 0x8a, 0x54, 0x2e, 0xb2, 0xe9,
	0x27, 0x19, 0x6e, 0x01, 0x4f, 0x93, 0x74, 0xac, 0x4b, 0xd1, 0xb5, 0xd5, 0xf7, 0x10, 0x82, 0xfd,
	0x45, 0x1c, 0x12, 0xe8, 0x85, 0x95, 0x9d, 0x94, 0xbc, 0x2e, 0x7b, 0x9b, 0x20, 0xc0, 0x7b, 0x08,
	0x4d, 0xa6, 0x03, 0x6f, 0x4b, 0x59, 0x35, 0xaa, 0xa2, 0x3a, 0xf2, 0xcc, 0x87, 0xfd, 0x33, 0xb8,
	0xc6, 0x0f, 0x53, 0xf0, 0x5f, 0xb9, 0x32, 0x65, 0x8b, 0x9b, 0x79, 0x39, 0xe3, 0x09, 0xb6, 0xe1,
	0x7f, 0x49, 0xef, 0xb4, 0xf0, 0xec, 0xbd, 0x9e, 0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x57, 0x2b,
	0x10, 0x8d, 0xc8, 0x01, 0x00, 0x00,
}
